version: '2'
services:

  # --------------------------------------------------------------
  # The Application
  amg-app:
    build:
      context: ./
      dockerfile: configs/app.dockerfile
    image: amg-app
    container_name: amg-app
    working_dir: /var/www
    volumes:
      - ../website:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=amg-db"
    depends_on:
      - amg-db

  # --------------------------------------------------------------
  # The Web Server
  amg-web:
    build:
      context: ./
      dockerfile: configs/web.dockerfile
    image: amg-web
    container_name: amg-web
    working_dir: /var/www
    volumes_from:
      - amg-app
    ports:
      - 8080:80
    depends_on:
      - amg-app

  # --------------------------------------------------------------
  # The Database
  amg-db:
    image: mysql:5.7
    container_name: amg-db
    volumes:
      - ../data/dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=amg_master"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33060:3306"

  # --------------------------------------------------------------
  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin
    environment:
      - "MYSQL_DATABASE=amg_master"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    links:
      - amg-db:db
    ports:
      - 8095:80

  # --------------------------------------------------------------
  # Percona PMM
  pmm:
    image: percona/pmm-server:latest
    container_name: pmm
    environment:
      - "SERVER_USER=admin"
      - "SERVER_PASSWORD=admin"
      - "ORCHESTRATOR_ENABLED=true"
      - "ORCHESTRATOR_USER=admin"
      - "ORCHESTRATOR_PASSWORD=admin"
    volumes:
      - "../data/pmmdata/prometheus:/opt/prometheus/data"
      - "../data/pmmdata/consul:/opt/consul-data"
      - "../data/pmmdata/mysql:/var/lib/mysql"
      - "../data/pmmdata/grafana:/var/lib/grafana"
    ports:
      - 8096:80
