#!/bin/bash
# --------------------------------------------------------------------------------
# Script name  : backup_db_full
# Author       : Dave Rix (dave@analysemy.golf)
# Created      : 2015-12-29
# Description  : This is a backup_db_full script to backup selected databases
# History      :
#  2015-12-29  : DAR - Initial script
# --------------------------------------------------------------------------------

# --------------------------------------------------------------------------------
# Variable Declaration and includes
# --------------------------------------------------------------------------------
# Include bash function library first
basePath=`git rev-parse --show-toplevel`
funcPath="${basePath}/funcs"
. ${funcPath}/funcs_bash

scriptDesc="AmG backup_db_full"
email="dave@analysemy.golf"

# --------------------------------------------------------------------------------
# Set some defaults
# --------------------------------------------------------------------------------

# --------------------------------------------------------------------------------
# Local functions
# --------------------------------------------------------------------------------
function AmG_RemoveTemp() {
	# Remove temp files if there are any
	doNothing=Y
}

function Script_Usage() {

	cat << EOF

usage: $0 OPTIONS server

OPTIONS can be:
        -h                Show this message
        -v                Verbose output

EOF

	# If we have called the usage statement, then something has gone wrong
	# so we can remove the lock file ready for the next run!
	AmG_Cleanup 1
}

# Now set up a trap to catch any errors and cause the exit early function to be
# called we will trap the following codes HUP, INT, QUIT, KILL
trap AmG_Exit_Early 1 2 3 9
# --------------------------------------------------------------------------------

# --------------------------------------------------------------------------------
# Check which options have been passed in
# --------------------------------------------------------------------------------
while getopts ":hv" OPTION
do
	case $OPTION in
		h)
			Script_Usage
			;;
		v)
			verbose="Y"
			;;
		?)
			Script_Usage
			;;
	esac
done
shift $((OPTIND - 1))

# --------------------------------------------------------------------------------

# --------------------------------------------------------------------------------
# We are ready to start, so check and set the lock file
# --------------------------------------------------------------------------------
AmG_Message "Starting ${scriptName} for localhost..."
AmG_ObtainLock
AmG_Verbose "Verbose logging  = ${verbose}"
# --------------------------------------------------------------------------------

# Ensure the folder is there
backupRoot="/data/mysql/backups"
mkdir -p ${backupRoot} 2>/dev/null
LSNfile=${backupRoot}/LSN.latest
backupPath="${backupRoot}/${theDTS}.full"
backupFile="${backupPath}.tar.gz"

# --------------------------------------------------------------------------------
# First, we backup the system using innobackupex
AmG_Message "Backing up databases"
innobackupex	--user=amg_backup --password=amg_backup \
				--no-timestamp ${backupPath}

# --------------------------------------------------------------------------------
# What is the LSN for this backup - used for the incrementals coming later
grep to_lsn ${backupPath}/xtrabackup_checkpoints | awk '{print $3+0}' > ${LSNfile}

# --------------------------------------------------------------------------------
# Now compress and tar up the backup
AmG_Message "Compressing and compacting backup"
tar -zcvf ${backupFile} ${backupPath}

# --------------------------------------------------------------------------------
# All done, so tidy stuff up a bit before exiting...
AmG_Cleanup
# --------------------------------------------------------------------------------
# --------------------------------------------------------------------------------
#      SCRIPT END
# --------------------------------------------------------------------------------
# --------------------------------------------------------------------------------
