#!/bin/bash
# --------------------------------------------------------------------------------
# Script name  : restore_db
# Author       : Dave Rix (dave@analysemy.golf)
# Created      : 2015-12-30
# Description  : This is a script to restore a database from full or partial
# History      :
#  2015-12-30  : DAR - Initial script
# --------------------------------------------------------------------------------

# --------------------------------------------------------------------------------
# Variable Declaration and includes
# --------------------------------------------------------------------------------
# Include bash function library first
basePath=`git rev-parse --show-toplevel`
funcPath="${basePath}/funcs"
. ${funcPath}/funcs_bash

scriptDesc="AmG restore_db"
email="dave@analysemy.golf"

# --------------------------------------------------------------------------------
# Set some defaults
# --------------------------------------------------------------------------------

# --------------------------------------------------------------------------------
# Local functions
# --------------------------------------------------------------------------------
function AmG_RemoveTemp() {
	# Remove temp files if there are any
	doNothing=Y
}

function Script_Usage() {

	cat << EOF

usage: $0 OPTIONS server

OPTIONS can be:
        -h                Show this message
        -v                Verbose output

EOF

	# If we have called the usage statement, then something has gone wrong
	# so we can remove the lock file ready for the next run!
	AmG_Cleanup 1
}

# Now set up a trap to catch any errors and cause the exit early function to be
# called we will trap the following codes HUP, INT, QUIT, KILL
trap AmG_Exit_Early 1 2 3 9
# --------------------------------------------------------------------------------

# --------------------------------------------------------------------------------
# Check which options have been passed in
# --------------------------------------------------------------------------------
while getopts ":hv" OPTION
do
	case $OPTION in
		h)
			Script_Usage
			;;
		v)
			verbose="Y"
			;;
		?)
			Script_Usage
			;;
	esac
done
shift $((OPTIND - 1))

# --------------------------------------------------------------------------------

# --------------------------------------------------------------------------------
# We are ready to start, so check and set the lock file
# --------------------------------------------------------------------------------
AmG_Message "Starting ${scriptName} for localhost..."
AmG_ObtainLock
AmG_Verbose "Verbose logging  = ${verbose}"
# --------------------------------------------------------------------------------

# Ensure the folder is there
backupRoot="/data/mysql/backups"
mkdir -p ${backupRoot} 2>/dev/null
LSNfile=${backupRoot}/LSN.latest

# Find the LSN from the relevant file
LSN='cat ${LSNfile}'

# --------------------------------------------------------------------------------
# Get the most recent full backup, and all the subsequent incrementals

# Stop MySQL first, if it is currently running
AmG_Message "Stopping MySQL if currently running"
service mysql stop

# Deal with the full backup first
AmG_Message "Locating latest full backup"
latestBackup=`find ${backupRoot} -maxdepth 1 -type f -name "*.full.tar.gz" | \
				sort -r | head --lines=1`

backupFile=`basename ${latestBackup}`
targetPath=`echo ${backupFile} | sed "s/.tar.gz$//"`
rm -rf ${backupRoot}/${targetPath}

AmG_Message "About to remove the following path - <Enter> to proceed..."
AmG_Message "    /data/mysql/data"
read ans
rm -rf /data/mysql/data
mkdir -p /data/mysql/data

AmG_Message "Unpacking latest full backup ${backupFile} into ${targetPath}..."
cd /
tar -xf ${latestBackup}

AmG_Message "Preparing files for restore"
BASEDIR=${backupRoot}/${targetPath}
innobackupex --apply-log --redo-only --use-memory=100M ${BASEDIR} > /dev/null

# Now loop for each of the incrementals
AmG_Message "Locating latest incremental backups"
incBackups=`find ${backupRoot} -maxdepth 1 -type f -name "*.inc.tar.gz" | \
				sort`

for file in ${incBackups}
do
	AmG_Message "   examining ${file}"
	if [ "${file}" \> "${latestBackup}" ]
	then
		AmG_Message "        newer than full backup ${latestBackup}"

		# Now repeat what we did with the full backup file
		incBackupFile=`basename ${file}`
		incTargetPath=`echo ${incBackupFile} | sed "s/.tar.gz$//"`

		rm -rf ${backupRoot}/${incTargetPath}

		AmG_Message "            unpacking..."
		cd /
		tar -xf ${file}

		AmG_Message "            combining with full backup..."
		INCDIR=${backupRoot}/${incTargetPath}
		innobackupex --apply-log --redo-only --use-memory=100M ${BASEDIR} --incremental-dir=${INCDIR} > /dev/null

		rm -rf ${INCDIR}

	fi

done

AmG_Message "Finalising backup by rolling back uncommitted transactions"
innobackupex --apply-log --use-memory=100M ${BASEDIR}

AmG_Message "Transferring backup files to original location"
innobackupex --copy-back ${BASEDIR}

AmG_Message "Starting MySQL"
service mysql start

AmG_Message "If all has completed successfully, the old backup path below can be removed."
AmG_Message "    ${BASEDIR}"

# --------------------------------------------------------------------------------
# All done, so tidy stuff up a bit before exiting...
AmG_Cleanup
# --------------------------------------------------------------------------------
# --------------------------------------------------------------------------------
#      SCRIPT END
# --------------------------------------------------------------------------------
# --------------------------------------------------------------------------------
